version: 2
updates:
  # Monitor GitHub Actions for security updates
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 10
    reviewers:
      - "michael-cerasulo"
    labels:
      - "dependencies"
      - "security"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    # Group all patch updates together to reduce PR noise
    groups:
      github-actions-patch:
        patterns:
          - "*"
        update-types:
          - "patch"
